name: hacker_news_extended
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  url_launcher: any
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^6.2.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  built_value_generator: ^6.2.0

flutter:
  uses-material-design: true
